#!/usr/bin/env bash

U=$(id -nu)
G=$(id -ng)

VER="8"
NAME="el${VER}cvmfs.sif"
SING_CONF="el${VER}cvmfs.sing"

if [[ "${1}" == "sandbox" ]]; then
    shift
    DO_SANDBOX="--sandbox --fix-perms"
    NAME="${NAME}_sandbox"
fi
[[ -e "${NAME}" ]] && rm -f "${NAME}"

singularity remote login -u asevcenc -p "$(< ~/gitlab_cern.token)" docker://gitlab-registry.cern.ch
singularity build --fakeroot ${DO_SANDBOX} "${NAME}" "${SING_CONF}" || { echo "Build failed!"; exit 1; }

[[ -n "${DO_SANDBOX}" ]] && sudo chown -R ${U}:${G} "${NAME}"
sudo chown -R ${U}:${G} "${SINGULARITY_CACHEDIR:-${HOME}/.singularity/cache}"

oras login -u robot-asevcenc+asevcenc_push -p $(< ~/registry-cern-robot.token) registry.cern.ch
oras push registry.cern.ch/asevcenc/$(basename ${NAME} .sif):latest ${NAME}:application/vnd.sylabs.sif.layer.v1.sif && echo "Done" || echo "Fail"

