#!/usr/bin/env bash

./get_alien_ca

podman login -u asevcenc -p "$(< ~/el7cvmfs_gitlab.token)" gitlab-registry.cern.ch

podman build --no-cache --rm --format docker -t gitlab-registry.cern.ch/asevcenc/el7cvmfs.dock/el8cvmfs:latest -f el8cvmfs.cont .
podman push gitlab-registry.cern.ch/asevcenc/el7cvmfs.dock/el8cvmfs:latest

rm -rf master.zip alien-cas-master

